grafana:
  replicas: 0
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    existingClaim: grafana
    size: 10Gi
    storageClassName: gp2-csi

  ingress:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

alertmanager:
  enabled: true

  config:
    route:
      group_by:
        - alertname
        - cluster
        - service
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: default

    receivers:
      - name: default

  alertmanagerSpec:
    replicas: 0
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

prometheus:
  prometheusSpec:
    replicas: 0
    retention: 15d
    retentionSize: 8GB

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1200Mi

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
